#This makefile is to install all the extra packages
#needed for FSIM on Fedora

default:
	yum install -y alsa-lib-devel
	yum install -y bison
	yum install -y cmake
	yum install -y curl-devel
	yum install -y cyrus-sasl-devel
	yum install -y doxygen
	yum install -y elfutils-libelf-devel
	yum install -y flex
	yum install -y fftw-devel
	yum install -y git
	yum install -y gl-manpages
	yum install -y glib2-devel
	yum install -y gcc-c++
	yum install -y glibc-devel
	yum install -y glibc-devel.i686
	yum install -y glibc-utils
	yum install -y gperftools
	yum install -y gnutls-devel
	yum install -y jemalloc
	yum install -y jemalloc-devel
	yum install -y kcachegrind
	yum install -y libdrm-devel
	yum install -y libgcc.i686
	yum install -y libjpeg-turbo-static
	yum install -y libpng-static
	yum install -y libstdc++.i686
	yum install -y libuuid-devel
	yum install -y libX11-devel
	yum install -y libXau-devel
	yum install -y libxcb-devel
	yum install -y libXdamage-devel
	yum install -y libXext-devel
	yum install -y libXfixes-devel
	yum install -y libXrandr-devel
	yum install -y libXrender-devel
	yum install -y libXxf86vm-devel
	yum install -y libxml-devel
	yum install -y libxml2-devel
	yum install -y libxml2-static
	yum install -y mesa-libGL-devel
	yum install -y mesa-libGLU
	yum install -y mesa-libGLU-devel
	yum install -y ncurses-devel
	yum install -y ncurses-static
	yum install -y openssl-static
	yum install -y perl-libintl
	yum install -y perl-Text-Unidecode
	yum install -y pixman-devel
	yum install -y pl
	yum install -y readline-devel
	yum install -y readline-static

#package not found:
#	yum install -y sasl2-devel

	yum install -y SDL-devel
	yum install -y SDL-static
	yum install -y subversion
	yum install -y texinfo
	yum install -y texlive-epstopdf-bin

#package not found:
#	yum install -y texlive-utils
#install whole texlive package instead
	yum install -y texlive

	yum install -y valgrind
	yum install -y valgrind-devel
	yum install -y xorg-x11-proto-devel
	yum install -y zlib-devel

